import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# V4 Real-Qwen Validation on Colab T4\n",
                "\n",
                "Run this notebook on Google Colab with **GPU: T4** runtime.\n",
                "\n",
                "**Runtime > Change runtime type > GPU > T4**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Install & Setup\n",
                "import sys\n",
                "import subprocess\n",
                "import os\n",
                "\n",
                "# Clone repo\n",
                "if not os.path.exists('/content/automovies'):\n",
                "    subprocess.run(['git', 'clone', 'https://github.com/asdfhgds/automovies.git'], check=True)\n",
                "    print('Repo cloned')\n",
                "else:\n",
                "    print('Repo already exists')\n",
                "\n",
                "%cd /content/automovies\n",
                "\n",
                "# Install package\n",
                "!pip install -e . -q 2>&1 | tail -5\n",
                "\n",
                "# Add src to path\n",
                "sys.path.insert(0, '/content/automovies/src')\n",
                "\n",
                "print('Setup complete')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify GPU Environment\n",
                "import torch\n",
                "import sys\n",
                "\n",
                "print(f'Python: {sys.version}')\n",
                "print(f'PyTorch: {torch.__version__}')\n",
                "print(f'CUDA available: {torch.cuda.is_available()}')\n",
                "print(f'CUDA version: {torch.version.cuda}')\n",
                "\n",
                "if torch.cuda.is_available():\n",
                "    print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
                "    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\n",
                "    print(f'CUDA capability: {torch.cuda.get_device_capability(0)}')\n",
                "else:\n",
                "    print('NO GPU - Runtime > Change runtime type > GPU > T4')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify Environment & Dependencies\n",
                "import subprocess\n",
                "\n",
                "# Git commit\n",
                "result = subprocess.run(['git', 'rev-parse', 'HEAD'], capture_output=True, text=True, cwd='/content/automovies')\n",
                "print(f'Git commit: {result.stdout.strip()}')\n",
                "\n",
                "# Transformers version\n",
                "import transformers\n",
                "print(f'Transformers: {transformers.__version__}')\n",
                "\n",
                "# BitsAndBytes (for 4-bit quantization)\n",
                "try:\n",
                "    import bitsandbytes\n",
                "    print(f'BitsAndBytes: {bitsandbytes.__version__}')\n",
                "except ImportError:\n",
                "    print('BitsAndBytes: NOT INSTALLED - installing...')\n",
                "    !pip install bitsandbytes -q\n",
                "    import bitsandbytes\n",
                "    print(f'BitsAndBytes: {bitsandbytes.__version__} (installed)')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify Movie Data Exists\n",
                "import os\n",
                "import json\n",
                "\n",
                "project_dir = '/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026'\n",
                "movie_index = os.path.join(project_dir, 'movie_index.json')\n",
                "\n",
                "if os.path.exists(movie_index):\n",
                "    with open(movie_index, 'r') as f:\n",
                "        idx = json.load(f)\n",
                "    print(f'Movie: {idx[\"movie\"][\"title\"]}')\n",
                "    print(f'Duration: {idx[\"movie\"][\"duration_sec\"]}s')\n",
                "    print(f'Scenes: {len(idx[\"scenes\"])}')\n",
                "    print('Movie data found')\n",
                "else:\n",
                "    print('Movie data NOT found at:', project_dir)\n",
                "    print('You need to upload the movie_index.json to this location')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Run V4 Validation (Real Qwen on T4)\n",
                "import time\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "print('=' * 60)\n",
                "print('STARTING V4 REAL-QWEN VALIDATION')\n",
                "print('=' * 60)\n",
                "\n",
                "start_time = time.time()\n",
                "\n",
                "# Run the validation script\n",
                "cmd = [\n",
                "    sys.executable,\n",
                "    'scripts/run_director_validation.py',\n",
                "    '--project', 'data/bc6384be-47a5-4ee8-8674-7ff861472026',\n",
                "    '--num-concepts', '6',\n",
                "    '--min-coverage', '0.4'\n",
                "]\n",
                "\n",
                "print(f'Command: {\" \".join(cmd)}')\n",
                "print('-' * 40)\n",
                "\n",
                "result = subprocess.run(cmd, cwd='/content/automovies', capture_output=True, text=True, timeout=1800)\n",
                "\n",
                "elapsed = time.time() - start_time\n",
                "\n",
                "print(f'Exit code: {result.returncode}')\n",
                "print(f'Runtime: {elapsed:.1f}s ({elapsed/60:.1f} min)')\n",
                "print('-' * 40)\n",
                "print('STDOUT:')\n",
                "print(result.stdout[-3000:] if len(result.stdout) > 3000 else result.stdout)\n",
                "if result.stderr:\n",
                "    print('-' * 40)\n",
                "    print('STDERR:')\n",
                "    print(result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Inspect Validation Reports\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "reports_dir = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/reports')\n",
                "\n",
                "for fname in ['director_validation.json', 'director_reasoning.md', 'validation_summary.json']:\n",
                "    fpath = reports_dir / fname\n",
                "    if fpath.exists():\n",
                "        print('\\n=== {} ==='.format(fname))\n",
                "        content = fpath.read_text(encoding='utf-8')\n",
                "        if fname.endswith('.json'):\n",
                "            data = json.loads(content)\n",
                "            print(json.dumps(data, indent=2)[:5000])\n",
                "            if len(content) > 5000:\n",
                "                print('... [truncated]')\n",
                "        else:\n",
                "            print(content[:5000])\n",
                "            if len(content) > 5000:\n",
                "                print('... [truncated]')\n",
                "    else:\n",
                "        print('\\n=== {} === NOT FOUND'.format(fname))"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Validate Plan Output (if exists)\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "plan_path = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/director_plan.json')\n",
                "if plan_path.exists():\n",
                "    with open(plan_path) as f:\n",
                "        plan = json.load(f)\n",
                "    \n",
                "    print('=== director_plan.json ===')\n",
                "    print(json.dumps(plan, indent=2)[:4000])\n",
                "    \n",
                "    # Validate plan structure\n",
                "    print('\\n=== PLAN VALIDATION ===')\n",
                "    if 'editorial_plan' in plan:\n",
                "        print('editorial_plan present')\n",
                "        ep = plan['editorial_plan']\n",
                "        if 'visual' in ep:\n",
                "            v = ep['visual']\n",
                "            print(\"  visual.scene_id: {}\".format(v.get('scene_id')))\n",
                "            print(\"  visual.start_sec: {}\".format(v.get('start_sec')))\n",
                "            print(\"  visual.end_sec: {}\".format(v.get('end_sec')))\n",
                "            print(\"  visual.source_fact_refs: {}\".format(v.get('source_fact_refs')))\n",
                "        if 'editing' in ep:\n",
                "            e = ep['editing']\n",
                "            for k in ['transition', 'pacing', 'rhythm', 'emphasis', 'repetition', 'purpose']:\n",
                "                print(\"  editing.{}: {}\".format(k, e.get(k)))\n",
                "        if 'audio' in ep:\n",
                "            a = ep['audio']\n",
                "            for k in ['movie_audio', 'narration', 'music']:\n",
                "            print(\"  audio.{}: {}\".format(k, a.get(k)))\n",
                "    else:\n",
                "        print('editorial_plan MISSING')\n",
                "    \n",
                "    if 'grounding_audit' in plan:\n",
                "        audit = plan['grounding_audit']\n",
                "        print(\"\\n  overall_valid: {}\".format(audit.get('overall_valid')))\n",
                "        print(\"  fact_validation.valid: {}\".format(audit.get('fact_validation', {}).get('valid')))\n",
                "        print(\"  editorial_validation.valid: {}\".format(audit.get('editorial_validation', {}).get('valid')))\n",
                "        if 'legacy_prose_audit' in audit and audit['legacy_prose_audit']:\n",
                "            lpa = audit['legacy_prose_audit']\n",
                "            print(\"  legacy.sufficient: {}\".format(lpa.get('sufficient')))\n",
                "            print(\"  legacy.coverage: {}\".format(lpa.get('coverage')))\n",
                "            print(\"  legacy.invented_terms: {}\".format(lpa.get('invented_terms')[:10]))\n",
                "else:\n",
                "    print('director_plan.json NOT FOUND')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Validation Summary\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "print('=' * 60)\n",
                "print('V4 VALIDATION SUMMARY')\n",
                "print('=' * 60)\n",
                "\n",
                "summary_path = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/reports/validation_summary.json')\n",
                "if summary_path.exists():\n",
                "    with open(summary_path) as f:\n",
                "        summary = json.load(f)\n",
                "    print(json.dumps(summary, indent=2))\n",
                "\n",
                "val_path = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/reports/director_validation.json')\n",
                "if val_path.exists():\n",
                "    with open(val_path) as f:\n",
                "        val = json.load(f)\n",
                "    print('\\nVerdict: {}'.format(val.get('verdict', 'UNKNOWN')))\n",
                "    print('Concepts generated: {}'.format(val.get('concepts_generated')))\n",
                "    print('Rejected: {}'.format(val.get('rejected_concepts')))\n",
                "    sel = val.get('selected_concept')\n",
                "    if sel:\n",
                "        print('Selected: {}'.format(sel.get('title')))\n",
                "        ev = sel.get('_evidence')\n",
                "        if ev:\n",
                "            print('  reference_coverage: {}'.format(ev.get('reference_coverage')))\n",
                "            print('  claim_coverage: {}'.format(ev.get('claim_coverage_detail')))\n",
                "            print('  claims: {}'.format(len(ev.get('claims', []))))\n",
                "    print('Plan: {}'.format('PASS' if val.get('plan') else 'FAIL'))\n",
                "    if val.get('plan_rejection'):\n",
                "        print('Plan rejection: {}'.format(val['plan_rejection'].get('reason')))\n",
                "    rt = val.get('runtime', {})\n",
                "    print('\\nLLM calls: {}'.format(rt.get('llm_calls')))\n",
                "    print('Regeneration rounds: {}'.format(rt.get('regeneration_rounds')))\n",
                "    print('Model: {}'.format(rt.get('model')))\n",
                "    print('GPU: {}'.format(rt.get('gpu')))\n",
                "    print('Total runtime: {}s'.format(rt.get('runtime_seconds', 'N/A')))\n",
                "\n",
                "print('\\n' + '=' * 60)\n",
                "print('V4 VALIDATION COMPLETE')\n",
                "print('=' * 60)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Export Artifacts for Download\n",
                "import shutil\n",
                "from pathlib import Path\n",
                "\n",
                "output_dir = Path('/content/validation_artifacts')\n",
                "output_dir.mkdir(exist_ok=True)\n",
                "\n",
                "reports_dir = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/reports')\n",
                "\n",
                "for fname in ['director_validation.json', 'director_reasoning.md', 'validation_summary.json']:\n",
                "    src = reports_dir / fname\n",
                "    if src.exists():\n",
                "        shutil.copy2(src, output_dir / fname)\n",
                "        print('Copied: {}'.format(fname))\n",
                "\n",
                "plan_path = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/director_plan.json')\n",
                "if plan_path.exists():\n",
                "    shutil.copy2(plan_path, output_dir / 'director_plan.json')\n",
                "    print('Copied: director_plan.json')\n",
                "\n",
                "# Create zip for download\n",
                "shutil.make_archive('/content/validation_artifacts', 'zip', output_dir)\n",
                "print('\\nCreated: /content/validation_artifacts.zip')\n",
                "print('Download from Files panel on the left')"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(r'C:\Users\hp\Documents\Default Project\automovies\V4_Colab_Validation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print('Notebook written successfully')