import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# V5 Full Pipeline Validation on Colab T4\n",
                "\n",
                "Run this notebook on Google Colab with **GPU: T4** runtime.\n",
                "\n",
                "**Runtime > Change runtime type > GPU > T4**\n",
                "\n",
                "This validates the complete V5 pipeline:\n",
                "1. V4 Grounded Creative Director → director_plan.json\n",
                "2. Grounded Script Generator → grounded_script.json\n",
                "3. Editorial Director → editorial_plan.json\n",
                "4. Editorial Decision List → editorial_decisions.json\n",
                "5. Timeline Builder → editorial_timeline.json\n",
                "6. TTS (Kokoro) → voice.wav\n",
                "7. FFmpeg Render → final_render.mp4\n",
                "8. QC Validation → pipeline_status.json"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Install & Setup\n",
                "import sys\n",
                "import subprocess\n",
                "import os\n",
                "\n",
                "# Clone repo\n",
                "if not os.path.exists('/content/automovies'):\n",
                "    subprocess.run(['git', 'clone', 'https://github.com/asdfhgds/automovies.git'], check=True)\n",
                "    print('Repo cloned')\n",
                "else:\n",
                "    print('Repo already exists')\n",
                "\n",
                "%cd /content/automovies\n",
                "\n",
                "# Install package\n",
                "!pip install -e . -q 2>&1 | tail -5\n",
                "\n",
                "# Add src to path\n",
                "sys.path.insert(0, '/content/automovies/src')\n",
                "\n",
                "print('Setup complete')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify GPU Environment\n",
                "import torch\n",
                "import sys\n",
                "\n",
                "print(f'Python: {sys.version}')\n",
                "print(f'PyTorch: {torch.__version__}')\n",
                "print(f'CUDA available: {torch.cuda.is_available()}')\n",
                "print(f'CUDA version: {torch.version.cuda}')\n",
                "\n",
                "if torch.cuda.is_available():\n",
                "    print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
                "    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\n",
                "    print(f'CUDA capability: {torch.cuda.get_device_capability(0)}')\n",
                "else:\n",
                "    print('NO GPU - Runtime > Change runtime type > GPU > T4')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify Environment & Dependencies\n",
                "import subprocess\n",
                "\n",
                "# Git commit\n",
                "result = subprocess.run(['git', 'rev-parse', 'HEAD'], capture_output=True, text=True, cwd='/content/automovies')\n",
                "print(f'Git commit: {result.stdout.strip()}')\n",
                "\n",
                "# Transformers version\n",
                "import transformers\n",
                "print(f'Transformers: {transformers.__version__}')\n",
                "\n",
                "# BitsAndBytes (for 4-bit quantization)\n",
                "try:\n",
                "    import bitsandbytes\n",
                "    print(f'BitsAndBytes: {bitsandbytes.__version__}')\n",
                "except ImportError:\n",
                "    print('BitsAndBytes: NOT INSTALLED - installing...')\n",
                "    !pip install bitsandbytes -q\n",
                "    import bitsandbytes\n",
                "    print(f'BitsAndBytes: {bitsandbytes.__version__} (installed)')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify Movie Data Exists\n",
                "import os\n",
                "import json\n",
                "\n",
                "project_dir = '/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026'\n",
                "movie_index = os.path.join(project_dir, 'movie_index.json')\n",
                "\n",
                "if os.path.exists(movie_index):\n",
                "    with open(movie_index, 'r') as f:\n",
                "        idx = json.load(f)\n",
                "    print(f'Movie: {idx[\"movie\"][\"title\"]}')\n",
                "    print(f'Duration: {idx[\"movie\"][\"duration_sec\"]}s')\n",
                "    print(f'Scenes: {len(idx[\"scenes\"])}')\n",
                "    print('Movie data found')\n",
                "else:\n",
                "    print('Movie data NOT found at:', project_dir)\n",
                "    print('You need to upload the movie_index.json to this location')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Run V5 FULL PIPELINE (Real Qwen + TTS + Render on T4)\n",
                "import time\n",
                "import subprocess\n",
                "import os\n",
                "\n",
                "print('=' * 60)\n",
                "print('STARTING V5 FULL PIPELINE VALIDATION')\n",
                "print('=' * 60)\n",
                "\n",
                "# Set environment variables for V5 pipeline\n",
                "os.environ['STUDIO_PROFILE'] = 'colab-gpu'\n",
                "os.environ['REQUIRE_REAL_LLM'] = 'true'\n",
                "os.environ['GROUNDED_DIRECTOR'] = 'true'\n",
                "os.environ['EDITORIAL_MODE'] = 'true'\n",
                "os.environ['VISION_ENRICHER'] = 'qwen3vl'\n",
                "os.environ['REQUIRE_REAL_TTS'] = 'true'\n",
                "os.environ['DIRECTOR_NUM_CONCEPTS'] = '6'\n",
                "os.environ['DIRECTOR_MIN_COVERAGE'] = '0.4'\n",
                "os.environ['EDITORIAL_TARGET_SEC'] = '90'\n",
                "os.environ['EDITORIAL_CREATIVE_TASK'] = ''\n",
                "\n",
                "print('Environment:')\n",
                "for k in ['STUDIO_PROFILE', 'REQUIRE_REAL_LLM', 'GROUNDED_DIRECTOR', 'EDITORIAL_MODE',\n",
                "           'VISION_ENRICHER', 'REQUIRE_REAL_TTS', 'DIRECTOR_NUM_CONCEPTS',\n",
                "           'DIRECTOR_MIN_COVERAGE', 'EDITORIAL_TARGET_SEC']:\n",
                "    print(f'  {k}={os.environ.get(k)}')\n",
                "print(f'  PYTHONPATH=/content/automovies')\n",
                "\n",
                "start_time = time.time()\n",
                "\n",
                "cmd = [\n",
                "    sys.executable,\n",
                "    'scripts/run_pipeline.py',\n",
                "    'run',\n",
                "    '--project-id', 'bc6384be-47a5-4ee8-8674-7ff861472026',\n",
                "    '--profile', 'colab-gpu'\n",
                "]\n",
                "\n",
                "print(f'\\nCommand: {\" \".join(cmd)}')\n",
                "print('-' * 40)\n",
                "\n",
                "env = os.environ.copy()\n",
                "env['PYTHONPATH'] = '/content/automovies'\n",
                "\n",
                "result = subprocess.run(cmd, cwd='/content/automovies', capture_output=True, text=True, timeout=7200, env=env)\n",
                "\n",
                "elapsed = time.time() - start_time\n",
                "\n",
                "print(f'Exit code: {result.returncode}')\n",
                "print(f'Runtime: {elapsed:.1f}s ({elapsed/60:.1f} min)')\n",
                "print('-' * 40)\n",
                "print('STDOUT:')\n",
                "print(result.stdout[-5000:] if len(result.stdout) > 5000 else result.stdout)\n",
                "if result.stderr:\n",
                "    print('-' * 40)\n",
                "    print('STDERR:')\n",
                "    print(result.stderr[-3000:] if len(result.stderr) > 3000 else result.stderr)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Inspect V5 Pipeline Outputs\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "project_dir = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026')\n",
                "\n",
                "artifacts = [\n",
                "    ('director_plan.json', project_dir / 'director_plan.json'),\n",
                "    ('grounded_script.json', project_dir / 'grounded_script.json'),\n",
                "    ('editorial_plan.json', project_dir / 'editorial_plan.json'),\n",
                "    ('editorial_decisions.json', project_dir / 'editorial_decisions.json'),\n",
                "    ('editorial_timeline.json', project_dir / 'editorial_timeline.json'),\n",
                "    ('script.json', project_dir / 'script.json'),\n",
                "    ('final_render.mp4', project_dir / 'renders' / 'final_render.mp4'),\n",
                "    ('pipeline_status.json', project_dir / 'pipeline_status.json'),\n",
                "    ('provider_manifest.json', project_dir / 'provider_manifest.json'),\n",
                "    ('segment_manifest.json', project_dir / 'segment_manifest.json'),\n",
                "]\n",
                "\n",
                "for name, path in artifacts:\n",
                "    if path.exists():\n",
                "        size = path.stat().st_size\n",
                "        print(f'✓ {name} ({size/1024:.1f} KB)')\n",
                "        if name.endswith('.json'):\n",
                "            with open(path) as f:\n",
                "                data = json.load(f)\n",
                "            print(f'  Keys: {list(data.keys())}')\n",
                "    else:\n",
                "        print(f'✗ {name} NOT FOUND')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Inspect V4 Director Output\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "reports_dir = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/reports')\n",
                "\n",
                "for fname in ['director_validation.json', 'director_reasoning.md']:\n",
                "    fpath = reports_dir / fname\n",
                "    if fpath.exists():\n",
                "        print('\\n=== {} ==='.format(fname))\n",
                "        content = fpath.read_text(encoding='utf-8')\n",
                "        if fname.endswith('.json'):\n",
                "            data = json.loads(content)\n",
                "            print(json.dumps(data, indent=2)[:5000])\n",
                "            if len(content) > 5000:\n",
                "                print('... [truncated]')\n",
                "        else:\n",
                "            print(content[:5000])\n",
                "            if len(content) > 5000:\n",
                "                print('... [truncated]')\n",
                "    else:\n",
                "        print('\\n=== {} === NOT FOUND'.format(fname))\n",
                "\n",
                "plan_path = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026/director_plan.json')\n",
                "if plan_path.exists():\n",
                "    with open(plan_path) as f:\n",
                "        plan = json.load(f)\n",
                "    print('\\n=== director_plan.json ===')\n",
                "    print(json.dumps(plan, indent=2)[:4000])\n",
                "    print('\\n=== PLAN VALIDATION ===')\n",
                "    if 'editorial_plan' in plan:\n",
                "        print('editorial_plan present')\n",
                "        ep = plan['editorial_plan']\n",
                "        if 'visual' in ep:\n",
                "            v = ep['visual']\n",
                "            print(\"  visual.scene_id: {}\".format(v.get('scene_id')))\n",
                "            print(\"  visual.start_sec: {}\".format(v.get('start_sec')))\n",
                "            print(\"  visual.end_sec: {}\".format(v.get('end_sec')))\n",
                "            print(\"  visual.source_fact_refs: {}\".format(v.get('source_fact_refs')))\n",
                "        if 'editing' in ep:\n",
                "            e = ep['editing']\n",
                "            for k in ['transition', 'pacing', 'rhythm', 'emphasis', 'repetition', 'purpose']:\n",
                "                print(\"  editing.{}: {}\".format(k, e.get(k)))\n",
                "        if 'audio' in ep:\n",
                "            a = ep['audio']\n",
                "            for k in ['movie_audio', 'narration', 'music']:\n",
                "                print(\"  audio.{}: {}\".format(k, a.get(k)))\n",
                "    else:\n",
                "        print('editorial_plan MISSING')\n",
                "    if 'grounding_audit' in plan:\n",
                "        audit = plan['grounding_audit']\n",
                "        print(\"\\n  overall_valid: {}\".format(audit.get('overall_valid')))\n",
                "        print(\"  fact_validation.valid: {}\".format(audit.get('fact_validation', {}).get('valid')))\n",
                "        print(\"  editorial_validation.valid: {}\".format(audit.get('editorial_validation', {}).get('valid')))\n",
                "else:\n",
                "    print('director_plan.json NOT FOUND')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Validation Summary\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "print('=' * 60)\n",
                "print('V5 VALIDATION SUMMARY')\n",
                "print('=' * 60)\n",
                "\n",
                "project_dir = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026')\n",
                "\n",
                "# Director validation\n",
                "val_path = project_dir / 'reports' / 'director_validation.json'\n",
                "if val_path.exists():\n",
                "    with open(val_path) as f:\n",
                "        val = json.load(f)\n",
                "    print('\\n--- Director ---')\n",
                "    print('Verdict: {}'.format(val.get('verdict', 'UNKNOWN')))\n",
                "    print('Concepts generated: {}'.format(val.get('concepts_generated')))\n",
                "    print('Rejected: {}'.format(val.get('rejected_concepts')))\n",
                "    sel = val.get('selected_concept')\n",
                "    if sel:\n",
                "        print('Selected: {}'.format(sel.get('title')))\n",
                "    print('Plan: {}'.format('PASS' if val.get('plan') else 'FAIL'))\n",
                "\n",
                "# Pipeline status\n",
                "status_path = project_dir / 'pipeline_status.json'\n",
                "if status_path.exists():\n",
                "    with open(status_path) as f:\n",
                "        status = json.load(f)\n",
                "    print('\\n--- Pipeline ---')\n",
                "    print('Status: {}'.format(status.get('status', 'UNKNOWN')))\n",
                "    print('Stages completed: {}'.format(status.get('stages_completed', [])))\n",
                "    if status.get('final_render'):\n",
                "        print('Final render: {}'.format(status['final_render']))\n",
                "\n",
                "# Final render check\n",
                "render_path = project_dir / 'renders' / 'final_render.mp4'\n",
                "if render_path.exists():\n",
                "    size = render_path.stat().st_size\n",
                "    print(f'\\n✓ FINAL RENDER: {size/1024/1024:.1f} MB')\n",
                "    print('  Path: {}'.format(render_path))\n",
                "else:\n",
                "    print('\\n✗ FINAL RENDER NOT FOUND')\n",
                "\n",
                "print('\\n' + '=' * 60)\n",
                "print('V5 VALIDATION COMPLETE')\n",
                "print('=' * 60)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Export Artifacts for Download\n",
                "import shutil\n",
                "from pathlib import Path\n",
                "\n",
                "output_dir = Path('/content/validation_artifacts')\n",
                "output_dir.mkdir(exist_ok=True)\n",
                "\n",
                "project_dir = Path('/content/automovies/data/bc6384be-47a5-4ee8-8674-7ff861472026')\n",
                "reports_dir = project_dir / 'reports'\n",
                "\n",
                "artifacts = [\n",
                "    ('director_validation.json', reports_dir / 'director_validation.json'),\n",
                "    ('director_reasoning.md', reports_dir / 'director_reasoning.md'),\n",
                "    ('director_plan.json', project_dir / 'director_plan.json'),\n",
                "    ('grounded_script.json', project_dir / 'grounded_script.json'),\n",
                "    ('editorial_plan.json', project_dir / 'editorial_plan.json'),\n",
                "    ('editorial_decisions.json', project_dir / 'editorial_decisions.json'),\n",
                "    ('editorial_timeline.json', project_dir / 'editorial_timeline.json'),\n",
                "    ('script.json', project_dir / 'script.json'),\n",
                "    ('pipeline_status.json', project_dir / 'pipeline_status.json'),\n",
                "    ('provider_manifest.json', project_dir / 'provider_manifest.json'),\n",
                "    ('segment_manifest.json', project_dir / 'segment_manifest.json'),\n",
                "]\n",
                "\n",
                "for name, src in artifacts:\n",
                "    if src.exists():\n",
                "        shutil.copy2(src, output_dir / name)\n",
                "        print('Copied: {}'.format(name))\n",
                "\n",
                "render_src = project_dir / 'renders' / 'final_render.mp4'\n",
                "if render_src.exists():\n",
                "    shutil.copy2(render_src, output_dir / 'final_render.mp4')\n",
                "    print('Copied: final_render.mp4')\n",
                "\n",
                "# Create zip for download\n",
                "shutil.make_archive('/content/validation_artifacts', 'zip', output_dir)\n",
                "print('\\nCreated: /content/validation_artifacts.zip')\n",
                "print('Download from Files panel on the left')"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(r'C:\Users\hp\Documents\Default Project\automovies\V5_Colab_Validation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print('V5 Notebook written successfully')