import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# V5 Full Pipeline Validation on Colab T4\n",
                "\n",
                "Run this notebook on Google Colab with **GPU: T4** runtime.\n",
                "\n",
                "**Runtime > Change runtime type > GPU > T4**\n",
                "\n",
                "This validates the complete V5 pipeline using the new **stage-oriented architecture**:\n",
                "1. `ingest` — Initialize project & register source\n",
                "2. `transcription` — WhisperX word-level transcription\n",
                "3. `scene_indexing` — PySceneDetect shot detection\n",
                "4. `movie_intelligence` — Enriched movie index (Qwen3-VL optional)\n",
                "5. `director` — Grounded creative director → `director_plan.json`\n",
                "6. `editorial` → `editorial_plan.json`, `editorial_timeline.json`, `script.json`\n",
                "7. `scene_selection` → `selected_scenes.json`\n",
                "8. `clip_extraction` → `assets/scenes/*.mp4`\n",
                "9. `visual_generation` (ComfyUI) → `assets/generated/*.png`\n",
                "10. `tts` (Kokoro) → `voice.wav`\n",
                "11. `render` (FFmpeg) → `final_render.mp4`\n",
                "12. `qc` → `pipeline_status.json`\n",
                "\n",
                "**All stages communicate via persistent artifacts in Google Drive.**\n",
                "You can run stages individually and resume after interruption."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Mount Google Drive\n",
                "from google.colab import drive\n",
                "drive.mount('/content/drive')\n",
                "print('Drive mounted')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Install & Setup\n",
                "import sys\n",
                "import subprocess\n",
                "import os\n",
                "\n",
                "# Clone repo\n",
                "if not os.path.exists('/content/automovies'):\n",
                "    subprocess.run(['git', 'clone', 'https://github.com/asdfhgds/automovies.git'], check=True)\n",
                "    print('Repo cloned')\n",
                "else:\n",
                "    print('Repo already exists')\n",
                "\n",
                "%cd /content/automovies\n",
                "\n",
                "# Install package\n",
                "!pip install -e . -q 2>&1 | tail -5\n",
                "\n",
                "# Add src to path\n",
                "sys.path.insert(0, '/content/automovies/src')\n",
                "\n",
                "print('Setup complete')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify GPU Environment\n",
                "import torch\n",
                "import sys\n",
                "\n",
                "print(f'Python: {sys.version}')\n",
                "print(f'PyTorch: {torch.__version__}')\n",
                "print(f'CUDA available: {torch.cuda.is_available()}')\n",
                "print(f'CUDA version: {torch.version.cuda}')\n",
                "\n",
                "if torch.cuda.is_available():\n",
                "    print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
                "    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\n",
                "    print(f'CUDA capability: {torch.cuda.get_device_capability(0)}')\n",
                "else:\n",
                "    print('NO GPU - Runtime > Change runtime type > GPU > T4')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Verify Environment & Dependencies\n",
                "import subprocess\n",
                "\n",
                "# Git commit\n",
                "result = subprocess.run(['git', 'rev-parse', 'HEAD'], capture_output=True, text=True, cwd='/content/automovies')\n",
                "print(f'Git commit: {result.stdout.strip()}')\n",
                "\n",
                "# Transformers version\n",
                "import transformers\n",
                "print(f'Transformers: {transformers.__version__}')\n",
                "\n",
                "# BitsAndBytes (for 4-bit quantization)\n",
                "try:\n",
                "    import bitsandbytes\n",
                "    print(f'BitsAndBytes: {bitsandbytes.__version__}')\n",
                "except ImportError:\n",
                "    print('BitsAndBytes: NOT INSTALLED - installing...')\n",
                "    !pip install bitsandbytes -q\n",
                "    import bitsandbytes\n",
                "    print(f'BitsAndBytes: {bitsandbytes.__version__} (installed)')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Configure Project & Google Drive Storage\n",
                "import os\n",
                "import json\n",
                "\n",
                "PROJECT_ID = 'bc6384be-47a5-4ee8-8674-7ff861472026'\n",
                "\n",
                "# Google Drive paths\n",
                "DRIVE_ROOT = '/content/drive/MyDrive/AutoMovies'\n",
                "MOVIES_DIR = os.path.join(DRIVE_ROOT, 'movies')\n",
                "PROJECTS_DIR = os.path.join(DRIVE_ROOT, 'projects')\n",
                "\n",
                "os.makedirs(MOVIES_DIR, exist_ok=True)\n",
                "os.makedirs(PROJECTS_DIR, exist_ok=True)\n",
                "\n",
                "# Project directories\n",
                "project_dir = os.path.join(PROJECTS_DIR, PROJECT_ID)\n",
                "os.makedirs(project_dir, exist_ok=True)\n",
                "for sub in ['transcripts', 'scenes', 'assets', 'renders', 'audio', 'reports']:\n",
                "    os.makedirs(os.path.join(project_dir, sub), exist_ok=True)\n",
                "\n",
                "print(f'Project: {PROJECT_ID}')\n",
                "print(f'Storage root: {PROJECTS_DIR}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Download/Verify Source Video from Google Drive\n",
                "import gdown\n",
                "import os\n",
                "\n",
                "# Replace with your Google Drive file IDs\n",
                "SOURCE_VIDEO_ID = ''  # e.g., '1ABC123...'\n",
                "SOURCE_VIDEO_NAME = 'source.mp4'\n",
                "\n",
                "source_path = os.path.join(project_dir, SOURCE_VIDEO_NAME)\n",
                "if os.path.exists(source_path):\n",
                "    print(f'✓ Source video already exists: {source_path}')\n",
                "elif SOURCE_VIDEO_ID:\n",
                "    print(f'Downloading source video...')\n",
                "    url = f'https://drive.google.com/uc?id={SOURCE_VIDEO_ID}'\n",
                "    gdown.download(url, source_path, quiet=False)\n",
                "    print(f'✓ Downloaded source video')\n",
                "else:\n",
                "    print('⚠ No source video ID provided')\n",
                "    print('  Upload your video to Google Drive, get shareable link ID, and set SOURCE_VIDEO_ID')\n",
                "\n",
                "# Create project_meta.json\n",
                "meta = {\n",
                "    'project_id': PROJECT_ID,\n",
                "    'title': 'Real Movie Vision Test',\n",
                "    'source_path': source_path if os.path.exists(source_path) else None\n",
                "}\n",
                "with open(os.path.join(project_dir, 'project_meta.json'), 'w') as f:\n",
                "    json.dump(meta, f, indent=2)\n",
                "print('✓ project_meta.json created')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Download/Verify Movie Intelligence from Google Drive (Optional)\n",
                "import os\n",
                "\n",
                "# If you already have movie_index.json from a previous run,\n",
                "# download it to skip the transcription + scene_indexing + movie_intelligence stages.\n",
                "MOVIE_INDEX_ID = ''  # e.g., '1XYZ789...'\n",
                "\n",
                "movie_index_path = os.path.join(project_dir, 'movie_index.json')\n",
                "if os.path.exists(movie_index_path):\n",
                "    print('✓ movie_index.json already exists')\n",
                "elif MOVIE_INDEX_ID:\n",
                "    import gdown\n",
                "    url = f'https://drive.google.com/uc?id={MOVIE_INDEX_ID}'\n",
                "    gdown.download(url, movie_index_path, quiet=False)\n",
                "    # Also download semantic_index.json\n",
                "    sem_path = os.path.join(project_dir, 'semantic_index.json')\n",
                "    if not os.path.exists(sem_path):\n",
                "        # Try to infer semantic index ID from movie_index ID\n",
                "        pass\n",
                "    print('✓ Downloaded movie_index.json')\n",
                "else:\n",
                "    print('⚠ No movie_index.json - will run full intelligence pipeline')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Run Pipeline Stages (Individual or All)\n",
                "import subprocess\n",
                "import sys\n",
                "import os\n",
                "\n",
                "print('=' * 60)\n",
                "print('STAGE RUNNER - AutoMovies Pipeline')\n",
                "print('=' * 60)\n",
                "\n",
                "# Set storage root to Google Drive\n",
                "os.environ['AUTOMOVIES_PROJECT_ROOT'] = PROJECTS_DIR\n",
                "\n",
                "def run_stage(stage_name, config=None, force=False, dry_run=False):\n",
                "    cmd = [\n",
                "        sys.executable,\n",
                "        'scripts/run_stage.py',\n",
                "        '--storage-root', PROJECTS_DIR,\n",
                "        '--project-id', PROJECT_ID,\n",
                "        '--stage', stage_name,\n",
                "    ]\n",
                "    if force:\n",
                "        cmd.append('--force')\n",
                "    if dry_run:\n",
                "        cmd.append('--dry-run')\n",
                "    if config:\n",
                "        for k, v in config.items():\n",
                "            cmd.extend(['--config', f'{k}={json.dumps(v)}'])\n",
                "    \n",
                "    print(f'\\n▶️  Running stage: {stage_name}')\n",
                "    print(f'   Command: {\" \".join(cmd)}')\n",
                "    result = subprocess.run(cmd, cwd='/content/automovies', capture_output=True, text=True, timeout=7200)\n",
                "    \n",
                "    print(f'Exit code: {result.returncode}')\n",
                "    if result.stdout:\n",
                "        print(result.stdout[-3000:] if len(result.stdout) > 3000 else result.stdout)\n",
                "    if result.stderr:\n",
                "        print('STDERR:')\n",
                "        print(result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr)\n",
                "    \n",
                "    return result.returncode == 0"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Option A: Run Full Pipeline (All Stages)\n",
                "print('Running FULL PIPELINE...')\n",
                "success = run_stage('all', \n",
                "    config={\n",
                "        'grounded': True,\n",
                "        'num_concepts': 6,\n",
                "        'min_coverage': 0.4,\n",
                "        'target_sec': 90,\n",
                "        'enricher': 'qwen3vl',\n",
                "        'provider': 'qwen',\n",
                "    },\n",
                "    force=False\n",
                ")\n",
                "\n",
                "if success:\n",
                "    print('\\n✅ FULL PIPELINE COMPLETED SUCCESSFULLY')\n",
                "else:\n",
                "    print('\\n❌ PIPELINE FAILED - check logs above')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Option B: Run Individual Stages (for debugging/resume)\n",
                "# Uncomment and run individual stages as needed:\n",
                "\n",
                "# Stage 1: Ingest (creates project_meta.json)\n",
                "# run_stage('ingest', config={'title': 'Real Movie Vision Test'})\n",
                "\n",
                "# Stage 2: Transcription\n",
                "# run_stage('transcription', config={'model': 'large-v3', 'word_timestamps': True})\n",
                "\n",
                "# Stage 3: Scene Indexing\n",
                "# run_stage('scene_indexing', config={'threshold': 30.0})\n",
                "\n",
                "# Stage 4: Movie Intelligence\n",
                "# run_stage('movie_intelligence', config={'enricher': 'qwen3vl', 'attach_keyframes': True, 'max_frames': 1})\n",
                "\n",
                "# Stage 5: Director\n",
                "# run_stage('director', config={'grounded': True, 'num_concepts': 6, 'min_coverage': 0.4, 'target_sec': 90})\n",
                "\n",
                "# Stage 6: Editorial\n",
                "# run_stage('editorial', config={'target_sec': 90})\n",
                "\n",
                "# Stage 7: Scene Selection\n",
                "# run_stage('scene_selection', config={'top_n': 3})\n",
                "\n",
                "# Stage 8: Clip Extraction\n",
                "# run_stage('clip_extraction', config={'codec': 'libx264', 'crf': 18})\n",
                "\n",
                "# Stage 9: Visual Generation (ComfyUI)\n",
                "# run_stage('visual_generation', config={'provider': 'comfyui'})\n",
                "\n",
                "# Stage 10: TTS\n",
                "# run_stage('tts', config={'provider': 'kokoro', 'emotion': 'neutral', 'pace': 1.0})\n",
                "\n",
                "# Stage 11: Render\n",
                "# run_stage('render', config={'codec': 'libx264', 'crf': 18, 'preset': 'medium'})\n",
                "\n",
                "# Stage 12: QC\n",
                "# run_stage('qc')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Inspect Pipeline Outputs\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "project_dir = Path(PROJECTS_DIR) / PROJECT_ID\n",
                "\n",
                "artifacts = [\n",
                "    ('project_manifest.json', project_dir / 'project_manifest.json'),\n",
                "    ('project_meta.json', project_dir / 'project_meta.json'),\n",
                "    ('movie_index.json', project_dir / 'movie_index.json'),\n",
                "    ('semantic_index.json', project_dir / 'semantic_index.json'),\n",
                "    ('director_plan.json', project_dir / 'director_plan.json'),\n",
                "    ('grounded_script.json', project_dir / 'grounded_script.json'),\n",
                "    ('editorial_plan.json', project_dir / 'editorial_plan.json'),\n",
                "    ('editorial_timeline.json', project_dir / 'editorial_timeline.json'),\n",
                "    ('script.json', project_dir / 'script.json'),\n",
                "    ('selected_scenes.json', project_dir / 'scenes' / 'selected_scenes.json'),\n",
                "    ('final_render.mp4', project_dir / 'renders' / 'final_render.mp4'),\n",
                "    ('pipeline_status.json', project_dir / 'reports' / 'pipeline_status.json'),\n",
                "    ('provider_manifest.json', project_dir / 'reports' / 'provider_manifest.json'),\n",
                "    ('qc_report.json', project_dir / 'reports' / 'qc_report.json'),\n",
                "]\n",
                "\n",
                "for name, path in artifacts:\n",
                "    if path.exists():\n",
                "        size = path.stat().st_size\n",
                "        print(f'✓ {name} ({size/1024:.1f} KB)')\n",
                "        if name.endswith('.json'):\n",
                "            with open(path) as f:\n",
                "                data = json.load(f)\n",
                "            print(f'  Keys: {list(data.keys())}')\n",
                "    else:\n",
                "        print(f'✗ {name} NOT FOUND')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Validation Summary\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                "project_dir = Path(PROJECTS_DIR) / PROJECT_ID\n",
                "\n",
                "print('=' * 60)\n",
                "print('V5 VALIDATION SUMMARY')\n",
                "print('=' * 60)\n",
                "\n",
                "# Project manifest\n",
                "manifest_path = project_dir / 'project_manifest.json'\n",
                "if manifest_path.exists():\n",
                "    with open(manifest_path) as f:\n",
                "        manifest = json.load(f)\n",
                "    print('\\n--- Project Manifest ---')\n",
                "    for stage_name in ['ingest', 'transcription', 'scene_indexing', 'movie_intelligence',\n",
                "                     'director', 'editorial', 'scene_selection', 'clip_extraction',\n",
                "                     'visual_generation', 'tts', 'render', 'qc']:\n",
                "        stage = manifest.get('stages', {}).get(stage_name, {})\n",
                "        status = stage.get('status', 'not_started')\n",
                "        icon = {'completed': '✅', 'running': '🔄', 'failed': '❌', \n",
                "              'skipped': '⏭️', 'not_started': '⭕'}.get(status, '❓')\n",
                "        print(f'  {icon} {stage_name}: {status} ({stage.get(\"duration_seconds\", 0):.1f}s)')\n",
                "\n",
                "# Pipeline status\n",
                "status_path = project_dir / 'reports' / 'pipeline_status.json'\n",
                "if status_path.exists():\n",
                "    with open(status_path) as f:\n",
                "        status = json.load(f)\n",
                "    print(f'\\n--- Pipeline Status ---')\n",
                "    print(f'Status: {status.get(\"status\", \"UNKNOWN\")}')\n",
                "    if status.get('reasons'):\n",
                "        for r in status['reasons']:\n",
                "            print(f'  - {r}')\n",
                "\n",
                "# Final render\n",
                "render_path = project_dir / 'renders' / 'final_render.mp4'\n",
                "if render_path.exists():\n",
                "    size = render_path.stat().st_size\n",
                "    print(f'\\n✅ FINAL RENDER: {size/1024/1024:.1f} MB')\n",
                "else:\n",
                "    print('\\n❌ FINAL RENDER NOT FOUND')\n",
                "\n",
                "print('\\n' + '=' * 60)\n",
                "print('V5 VALIDATION COMPLETE')\n",
                "print('=' * 60)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title Export Artifacts for Download\n",
                "import shutil\n",
                "from pathlib import Path\n",
                "\n",
                "output_dir = Path('/content/validation_artifacts')\n",
                "output_dir.mkdir(exist_ok=True)\n",
                "\n",
                "project_dir = Path(PROJECTS_DIR) / PROJECT_ID\n",
                "\n",
                "artifacts = [\n",
                "    ('project_manifest.json', project_dir / 'project_manifest.json'),\n",
                "    ('project_meta.json', project_dir / 'project_meta.json'),\n",
                "    ('movie_index.json', project_dir / 'movie_index.json'),\n",
                "    ('semantic_index.json', project_dir / 'semantic_index.json'),\n",
                "    ('director_plan.json', project_dir / 'director_plan.json'),\n",
                "    ('grounded_script.json', project_dir / 'grounded_script.json'),\n",
                "    ('editorial_plan.json', project_dir / 'editorial_plan.json'),\n",
                "    ('editorial_timeline.json', project_dir / 'editorial_timeline.json'),\n",
                "    ('script.json', project_dir / 'script.json'),\n",
                "    ('selected_scenes.json', project_dir / 'scenes' / 'selected_scenes.json'),\n",
                "    ('pipeline_status.json', project_dir / 'reports' / 'pipeline_status.json'),\n",
                "    ('provider_manifest.json', project_dir / 'reports' / 'provider_manifest.json'),\n",
                "    ('qc_report.json', project_dir / 'reports' / 'qc_report.json'),\n",
                "]\n",
                "\n",
                "for name, src in artifacts:\n",
                "    if src.exists():\n",
                "        shutil.copy2(src, output_dir / name)\n",
                "        print('Copied: {}'.format(name))\n",
                "\n",
                "render_src = project_dir / 'renders' / 'final_render.mp4'\n",
                "if render_src.exists():\n",
                "    shutil.copy2(render_src, output_dir / 'final_render.mp4')\n",
                "    print('Copied: final_render.mp4')\n",
                "\n",
                "# Create zip for download\n",
                "shutil.make_archive('/content/validation_artifacts', 'zip', output_dir)\n",
                "print('\\nCreated: /content/validation_artifacts.zip')\n",
                "print('Download from Files panel on the left')"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(r'C:\Users\hp\Documents\Default Project\automovies\V5_Colab_Validation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print('V5 Notebook written successfully')